// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eypbbsbprbeteolxghoe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV5cGJic2JwcmJldGVvbHhnaG9lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MzY4ODYsImV4cCI6MjA2NTUxMjg4Nn0.CT0sHUTSDX6hmQtN089PRARnkx-ktFWoNT1QDpDeYqU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);